/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EsIndexRouteImport } from './routes/es/index'
import { Route as YachtsRoyalSunseekerSmuRouteImport } from './routes/yachts.royal-sunseeker-smu'
import { Route as AddOnsCateringRouteImport } from './routes/add-ons.catering'

const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EsIndexRoute = EsIndexRouteImport.update({
  id: '/es/',
  path: '/es/',
  getParentRoute: () => rootRouteImport,
} as any)
const YachtsRoyalSunseekerSmuRoute = YachtsRoyalSunseekerSmuRouteImport.update({
  id: '/yachts/royal-sunseeker-smu',
  path: '/yachts/royal-sunseeker-smu',
  getParentRoute: () => rootRouteImport,
} as any)
const AddOnsCateringRoute = AddOnsCateringRouteImport.update({
  id: '/add-ons/catering',
  path: '/add-ons/catering',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRoute
  '/thank-you': typeof ThankYouRoute
  '/add-ons/catering': typeof AddOnsCateringRoute
  '/yachts/royal-sunseeker-smu': typeof YachtsRoyalSunseekerSmuRoute
  '/es/': typeof EsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRoute
  '/thank-you': typeof ThankYouRoute
  '/add-ons/catering': typeof AddOnsCateringRoute
  '/yachts/royal-sunseeker-smu': typeof YachtsRoyalSunseekerSmuRoute
  '/es': typeof EsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRoute
  '/thank-you': typeof ThankYouRoute
  '/add-ons/catering': typeof AddOnsCateringRoute
  '/yachts/royal-sunseeker-smu': typeof YachtsRoyalSunseekerSmuRoute
  '/es/': typeof EsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/thank-you'
    | '/add-ons/catering'
    | '/yachts/royal-sunseeker-smu'
    | '/es/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/thank-you'
    | '/add-ons/catering'
    | '/yachts/royal-sunseeker-smu'
    | '/es'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/thank-you'
    | '/add-ons/catering'
    | '/yachts/royal-sunseeker-smu'
    | '/es/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRoute
  ThankYouRoute: typeof ThankYouRoute
  AddOnsCateringRoute: typeof AddOnsCateringRoute
  YachtsRoyalSunseekerSmuRoute: typeof YachtsRoyalSunseekerSmuRoute
  EsIndexRoute: typeof EsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/': {
      id: '/es/'
      path: '/es'
      fullPath: '/es/'
      preLoaderRoute: typeof EsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yachts/royal-sunseeker-smu': {
      id: '/yachts/royal-sunseeker-smu'
      path: '/yachts/royal-sunseeker-smu'
      fullPath: '/yachts/royal-sunseeker-smu'
      preLoaderRoute: typeof YachtsRoyalSunseekerSmuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-ons/catering': {
      id: '/add-ons/catering'
      path: '/add-ons/catering'
      fullPath: '/add-ons/catering'
      preLoaderRoute: typeof AddOnsCateringRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRoute,
  ThankYouRoute: ThankYouRoute,
  AddOnsCateringRoute: AddOnsCateringRoute,
  YachtsRoyalSunseekerSmuRoute: YachtsRoyalSunseekerSmuRoute,
  EsIndexRoute: EsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
